apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-for-appset-test
  namespace: argocd
  labels:
    for: jpmc
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: source-apps/application-set/generators
    repoURL: https://github.com/OpsMx/argo-customer-demo
    targetRevision: test1
  syncPolicy:
    #automated: {}
    syncOptions:
      - CreateNamespace=true
