apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-for-rollback
  namespace: argocd
  labels:
     for: jpmc
spec:
  destination:
    namespace: argocd-kt
    server: 'https://kubernetes.default.svc'
  source:
    path: source-data/test
    repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'
    targetRevision: gitreqtest1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
