apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-global-sync-timeout
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/your-repo.git  # Replace with your repo URL
    targetRevision: main
    path: config  # Replace with the correct path containing the ConfigMap YAML
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
