# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: sync-wait-job
# spec:
#   template:
#     spec:
#       containers:
#         - name: wait-container
#           image: busybox
#           command: ["sh", "-c", "sleep 300"]  # Introduce a delay of 25 seconds
#           volumeMounts:
#             - name: dummy-config
#               mountPath: /etc/dummy
#       volumes:
#         - name: dummy-config
#           configMap:
#             name: dummy-configmap
#       restartPolicy: Never
---
apiVersion: v1
data:
  foo: bar
  goo: car
  test: trial
  benda: beera
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm, Delete=confirm
  name: somecm
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: +++++++dXNlcm5hbWU=  # Base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
