apiVersion: v1
kind: ConfigMap
metadata:
  name: somecm1
data:
  foo: bar
  benda: beera
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret1
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-wait-job1
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"  # Runs before other resources
spec:
  template:
    spec:
      containers:
        - name: wait-container
          image: busybox
          command: ["sh", "-c", "sleep 4000"]  # Ensures sync takes over 1 hour
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: sync-wait-job2
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      containers:
        - name: wait-container
          image: busybox
          command: ["sh", "-c", "while true; do sleep 3600; done"]
          volumeMounts:
            - name: dummy-config
              mountPath: /etc/dummy
      volumes:
        - name: dummy-config
          configMap:
            name: somecm1
      restartPolicy: Never
