apiVersion: batch/v1
kind: Job
metadata:
  name: sync-wait-job
  annotations:
    argocd.argoproj.io/hook: PreSync  # Ensures this job runs before syncing other resources
spec:
  template:
    spec:
      containers:
        - name: wait-container
          image: busybox
          command: ["sh", "-c", "sleep 120"]  # Introduce a delay of 25 seconds
      restartPolicy: Never
---
apiVersion: v1
data:
  foo: bar
  goo: car
  test: trial
  benda: beera
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: somecm
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: +++++++dXNlcm5hbWU=  # Base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
