apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progressive-syncs-allatonce
  namespace: argocd
  labels:
    for: jpmc
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: progressive-syncs/allatonce
    repoURL: https://github.com/OpsMx/argo-customer-demo
    targetRevision: testcase
  syncPolicy:
    automated: {}
    syncOptions:
     - CreateNamespace=true
