apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-syncwave
  namespace: argocd
  labels:
    for: jpmc
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: progressive-syncs/rolling-sync
    repoURL: https://github.com/OpsMx/argo-customer-demo
    targetRevision: testcase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
