apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:invalid-tag.1.19
        ports:
        - containerPort: 80
