apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myplugin
  namespace: argocd
spec:
  generators:
    - plugin:
        configMapRef:
          name: applicationset-hello-plugin
  template:
    metadata:
      name: "from-appset-{{hello}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/bitthalpatidar/applicationset-hello-plugin.git
        path: .
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: "my-{{hello}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
