
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multicm-myplugin
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        configMapRef:
          name: applicationset-hello-plugin
        input:
          parameters:
            repo: "OpsMx/argo-customer-demo"
            branch: "testcase"
            folder: "source-data/configmap"
        requeueAfterSeconds: 60
  template:
    metadata:
      name: "multicm-myplugin"
      annotations:
        example.from.plugin.output: "{{ .contents }}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/OpsMx/argo-customer-demo.git"
        path: source-data/multicm-plugin-helm
        targetRevision: testcase
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  templatePatch: |
    spec:
      source:
        helm:
          parameters:
          {{- if .contents }}
          {{- range $fileName, $fileContents := .contents }}
            - name: 'configMapFiles.{{ $fileName | replace "." "\\." }}'
              value: '{{ $fileContents }}'
          {{- end }}
            - name: "name"
              value: '{{.name}}'
          {{- end }}
