apiVersion: v1
data:
  foo: bar
  goo: car
  test: trial
  benda: beera
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: somecm
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU=  # Base64 encoded value of "username"
  password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
