apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-applications
spec:
  generators:
    - git:
        repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'  # Replace with your actual repo URL
        revision: new-test
        directory:
          recurse: true
          path: 'source-apps/**'  # Root directory containing all applications
  template:
    metadata:
      labels:
        app: all-applications
    spec:
      project: default
      source:
        repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'  # Same as above
        targetRevision: new-test
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: source-apps-appset
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#     - git:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git 
#         revision: new-test
#         files:
#           - path: appset-directories.json
#   template:
#     metadata:
#       name: "{{ .path | replace '/' '-' }}"
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         targetRevision: new-test
#         path: '{{ .path }}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: test
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
