apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: source-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        revision: new-test
        files:
          - path: "source-apps/**/*.yaml"  # ✅ Recursively include all YAML manifests
        values:
          base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}"
  template:
    metadata:
      name: '{{ .path.basename }}'  # ✅ Dynamic name based on the file
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: "new-test"
        path: "{{ .values.base_dir }}"  # ✅ Correct path reference
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
