apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        revision: new-test
        files:
          - path: "source-apps/*/config.json"  # Reads config.json from subdirectories
  template:
    metadata:
      name: "app1"  
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: new-test
        path: "{{ .appPath }}"  # Uses appPath from config.json
        directory:
          recurse: true  # Ensures all YAML files in subdirectories are included
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: source-apps
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#   - git:
#       repoURL: https://github.com/OpsMx/argo-customer-demo.git
#       revision: new-test
#       files:
#         - path: "source-apps/**/config.json"  # This will recursively include all .yaml files under the source-apps directory
#       values:
#         base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}" #/{{index .path.segments 2}}"

#   template:
#     metadata:
#       name: '{{ .newPath.basename }}'  # Dynamic name based on the file being deployed
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         targetRevision: "new-test"
#         #path: "{{ .values.base_dir }}/global-sync"
#         path: "{{ .newPath }}"  # Use the base_dir to target the correct path
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: test
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true  # Use the basename of the application directory for the namespace



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: source-apps
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#   - git:
#       repoURL: https://github.com/OpsMx/argo-customer-demo.git
#       revision: new-test
#       files:
#         - path: "source-apps/applications/config.json"  # This will recursively include all .yaml files under the source-apps directory
#       values:
#         base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}" #/{{index .path.segments 2}}"

#   template:
#     metadata:
#       name: '{{ .path.basename }}-{{index .path.segments 1}}'  # Dynamic name based on the file being deployed
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         targetRevision: "new-test"
#         #path: "{{ .values.base_dir }}/global-sync"
#         path: "{{ .values.base_dir }}/global-sync"  # Use the base_dir to target the correct path
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: test
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true  # Use the basename of the application directory for the namespace

