apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: source-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/OpsMx/argo-customer-demo.git
      revision: new-test
      files:
        - path: "source-apps/*/config.json"  # This will recursively include all .yaml files under the source-apps directory
      # values:
      #   base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}" #/{{index .path.segments 2}}"

  template:
    metadata:
      name: '{{ .newPath.basename }}-{{index .newPath.segments 1}}'  # Dynamic name based on the file being deployed
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: "new-test""
        #path: "{{ .values.base_dir }}"  # Use the base_dir to target the correct path
        path: "{{index .newPath.segments 0}}/{{index .newPath.segments 1}}/{{index .newPath.segments 2}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true  '# Use the basename of the application directory for the namespace
        syncOptions:
          - CreateNamespace=true
          



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: source-apps
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#   - git:
#       repoURL: https://github.com/OpsMx/argo-customer-demo.git
#       revision: new-test
#       files:
#         - path: "source-apps/applications/config.json"  # This will recursively include all .yaml files under the source-apps directory
#       values:
#         base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}" #/{{index .path.segments 2}}"

#   template:
#     metadata:
#       name: '{{ .path.basename }}-temp'  # Dynamic name based on the file being deployed
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         targetRevision: "new-test"
#         #path: "{{ .values.base_dir }}/global-sync"
#         path: "{{ .values.base_dir }}/global-sync"  # Use the base_dir to target the correct path
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: test
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true  # Use the basename of the application directory for the namespace

