apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: source-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        revision: new-test
        files:
          - path: "source-apps/*/config.json"  # Path to the config.json files
  template:
    metadata:
      name: '{{ .path.basename }}'  # Dynamic name based on the file
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: "new-test"
        path: '{{ .path }}'  # This will be the path from the config.json
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true



# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: source-apps
#   namespace: argocd
# spec:
#   goTemplate: true
#   goTemplateOptions: ["missingkey=error"]
#   generators:
#     - git:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         revision: new-test
#         files:
#           - path: "source-apps/*/config.json"  # ✅ Recursively include all YAML manifests
#         # values:
#         #   base_dir: "{{index .path.segments 0}}/{{index .path.segments 1}}"
#   template:
#     metadata:
#       name: '{{ .path.basename }}'  # ✅ Dynamic name based on the file
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/OpsMx/argo-customer-demo.git
#         targetRevision: "new-test"
#         #path: "{{ .path }}" # ✅ Correct path reference
#         #path: source-apps/applications/global-sync
#         path: '{{ .path }}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: test
#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true
