apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: source-apps-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git 
        revision: new-test
        files:
          - path: appset-directories.json
  template:
    metadata:
      name: "{{ .path | replace '/' '-' }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: new-test
        path: '{{ .path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
