apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-git-1-helm-app
  namespace: argocd
  labels:
    for: jpmc
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-kt1
  sources:
    - repoURL: https://github.com/OpsMx/argo-customer-demo.git
      path: source-data/combination-sources-data/1-git-1-helm/1-git
      targetRevision: testcase
    - repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'
      path: source-data/combination-sources-data/1-git-1-helm/1-helm
      targetRevision: testcase
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
