apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-global-sync-timeout
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  project: default
  source:
    repoURL: https://github.com/OpsMx/argo-customer-demo.git  # Replace with your repo URL
    targetRevision: testcase
    path: cm  # Replace with the correct path containing the ConfigMap YAML
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
