apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-progressive-allatonce
  namespace: argocd
spec:
  strategy:
    type: AllAtOnce
  syncPolicy:
    #preserveResourcesOnDeletion: false               
    applicationsSync: create-only
    #applicationsSync: create-update
    #applicationsSync: create-delete
    #preserveResourcesOnDeletion: false
    #preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/OpsMx/argo-customer-demo.git
          revision: testcase
          files:
          - path: "addons/cmapp/dev/config.json"
      - list:
          elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
              namespace: ns1
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
               namespace: ns2
          # - cluster: in-cluster
          #   url: https://kubernetes.default.svc
          #   values:
          #     namespace: ns3
  template:
    metadata:
      name: '{{.name}}-{{.values.namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/OpsMx/argo-customer-demo.git
        targetRevision: testcase
        path: configmap
      destination:
        server: '{{.url}}'
        namespace: '{{.values.namespace}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PrunePropagationPolicy=orphan
