apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: argocd-kt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx12
        image: nginx:1.19
        ports:
        - containerPort: 80
